spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: jdbc:mysql://localhost:3306/mandu?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 19970923
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  devtools:
    # Auto Restart
    restart:
      enabled: true
      additional-exclude: static/**,public/**
    livereload:
      enabled: true


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
